name: Publish Main Branch to Server

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Deploy to Namecheap
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: server329.web-hosting.com
        username: lesaueqw
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 21
        server-dir: api/
